//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eligo.DataLayer.Tenants.EligoDb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EligoDbResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EligoDbResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eligo.DataLayer.Tenants.EligoDb.Resources.EligoDbResources", typeof(EligoDbResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı eposta olarak belirtilmelidir..
        /// </summary>
        internal static string EmailAddressMustHasAnEmailAddressFormat {
            get {
                return ResourceManager.GetString("EmailAddressMustHasAnEmailAddressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2508226|Wilaya de Aïn Defla|2589581
        ///2507899|Wilaya de Aïn Temouchent|2589581
        ///2505569|Wilaya de Batna|2589581
        ///2505325|Wilaya de Bejaïa|2589581
        ///2503822|Wilaya de Biskra|2589581
        ///2503765|Wilaya de Blida|2589581
        ///2503699|Wilaya de Bordj Bou Arréridj|2589581
        ///2502951|Wilaya de Bouira|2589581
        ///2502638|Wilaya de Boumerdes|2589581
        ///2505525|Wilaya de Béchar|2589581
        ///2501296|Wilaya de Chlef|2589581
        ///2501147|Wilaya de Constantine|2589581
        ///2500013|Wilaya de Djelfa|2589581
        ///2496045|Wilaya de Ghardaïa|2589581
        ///249565 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefCity {
            get {
                return ResourceManager.GetString("RefCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2589581|Algeria
        ///3351879|Angola
        ///2395170|Benin
        ///933860|Botswana
        ///2361809|Burkina Faso
        ///433561|Burundi
        ///2233387|Cameroon
        ///3374766|Cape Verde
        ///239880|Central African Republic
        ///2434508|Chad
        ///921929|Comoros
        ///203312|Congo
        ///223816|Djibouti
        ///357994|Egypt
        ///2309096|Equatorial Guinea
        ///338010|Eritrea
        ///337996|Ethiopia
        ///2400553|Gabon
        ///2413451|Gambia
        ///2300660|Ghana
        ///2420477|Guinea
        ///2372248|Guinea-Bissau
        ///2287781|Ivory Coast
        ///192950|Kenya
        ///932692|Lesotho
        ///2275384|Liberia
        ///2215636|Libya
        ///1062947|Madagascar
        ///927384|Malawi
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefCountry {
            get {
                return ResourceManager.GetString("RefCountry", resourceCulture);
            }
        }
    }
}
